export const music = /*html*/`
            <section class="hidden">
                <div class="music" id="music-section">
            <h2>Music</h2>
            <div>
                <p>What ties everything together for me has always been music, playing guitar from a young age,
                <br>and picking up more instruments as I grow.<br>For the games I make and just for pure fun and creative outlet, 
                <br>I play and produce some music, here are some tunes I've made, hope you enjoy!
                </p>
            </div>
            <div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030798&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/french-bot-tragedy" title="French Bot Tragedy" target="_blank" style="color: #cccccc; text-decoration: none;">French Bot Tragedy</a></div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030810&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/finally" title="Finally" target="_blank" style="color: #cccccc; text-decoration: none;">Finally</a></div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030789&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/miami-vice" title="Miami Vice" target="_blank" style="color: #cccccc; text-decoration: none;">Miami Vice</a></div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030822&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/dusk-drive" title="Dusk Drive" target="_blank" style="color: #cccccc; text-decoration: none;">Dusk Drive</a></div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030858&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/desert-flow" title="Desert Flow" target="_blank" style="color: #cccccc; text-decoration: none;">Desert Flow</a></div>
                <iframe width="100%" height="90" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1345030834&color=%23d4447c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/guy-ginat-548264090" title="Guy Ginat" target="_blank" style="color: #cccccc; text-decoration: none;">Guy Ginat</a> · <a href="https://soundcloud.com/guy-ginat-548264090/dream" title="Dream" target="_blank" style="color: #cccccc; text-decoration: none;">Dream</a></div>
                </div>
            </div>
            </section>
        `